Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,7 @@
 name: Update csv
 
 on:
+  push:
   schedule:
     # * is a special character in YAML so you have to quote this string
     - cron:  '*/30 * * * *'
@@ -31,16 +32,16 @@ jobs:
       run: |
         git config --local user.email "action@github.com"
         git config --local user.name "github-actions"
-        git add --all
-        if [-z "$(git status --porcelain)"]; then
-           echo "::set-output name=push::false"
+        git add .
+        set +e  # Grep succeeds with nonzero exit codes to show results.
+        git status | grep modified
+        if [ $? -eq 0 ]
+        then
+            set -e
+            git commit -am "update"
+            git push
         else
-           git commit -m "Add changes" -a
-           echo "::set-output name=push::true"
+            set -e
+            echo "No changes since last run"
         fi
       shell: bash
-    - name: Push changes
-      if: steps.commit.outputs.push == 'true'
-      uses: ad-m/github-push-action@master
-      with:
-         github_token: ${{ secrets.GITHUB_TOKEN }}
